export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as Platform} from './Platform'
export {default as Solution} from './Solution'
export {default as Resources} from './Resources'
export {default as About} from './About'
export {default as Contact} from './Contact'